spring:
  application:
    name: Bibliotheque
  # h2:
  #   console:
  #     enabled: true
  jpa:
    defer-datasource-initialization: true
    database-platform: org.hibernate.dialect.H2Dialect
    hibernate:
      ddl-auto: none
  datasource:
    url: jdbc:postgresql://localhost:5432/Brief15_Bibliotheque_Flyway
    # driverClassName: org.h2.Driver
    username: postgres
    password: postgres
  flyway: #flyway automatically uses the datasource from the application to connect to the DB
    enabled: true # enables flyway database migration
    locations: db/migration/structure, db/migration/data # the location where flyway should look for migration scripts
    validate-on-migrate: true